# spring:
#   application:
#     name: product-service
  # datasource:
  #   url: jdbc:postgresql://localhost:5434/productdb
  #   username: postgres
  #   password: password
  #   driver-class-name: org.postgresql.Driver
  # jpa:
  #   hibernate:
  #     ddl-auto: update
spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    compatibility-verifier:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt: {}
server:
  port: 8081






    